# Generated by Django 5.2.17 on 2026-09-12 13:34

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetTier',
            fields=[
                ('key', models.SlugField(max_length=32, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=32)),
                ('hint', models.CharField(blank=True, help_text="Ör: 'çay-simit'", max_length=64)),
                ('ratio_min', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=8)),
                ('ratio_max', models.DecimalField(blank=True, decimal_places=6, help_text='Boş = üst sınır yok', max_digits=8, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Bütçe kademesi',
                'verbose_name_plural': 'Bütçe kademeleri',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RemoteConfig',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('value', models.JSONField()),
                ('note', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Uzaktan ayar',
                'verbose_name_plural': 'Uzaktan ayarlar',
            },
        ),
        migrations.CreateModel(
            name='WeeklyTheme',
            fields=[
                ('key', models.SlugField(max_length=48, primary_key=True, serialize=False)),
                ('label', models.CharField(help_text='Sadece yönetim için', max_length=80)),
                ('starts_on', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Haftalık tema',
                'verbose_name_plural': 'Haftalık temalar',
                'ordering': ['-starts_on'],
            },
        ),
        migrations.CreateModel(
            name='AnonProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anon_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('disliked_categories', models.JSONField(blank=True, default=list)),
                ('locale', models.CharField(default='tr', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('budget_tier_default', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.budgettier')),
            ],
            options={
                'verbose_name': 'Anonim kullanıcı',
                'verbose_name_plural': 'Anonim kullanıcılar',
            },
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('source', models.CharField(choices=[('seed', 'Seed'), ('ai', 'AI')], default='seed', max_length=8)),
                ('title', models.CharField(help_text='En fazla 6 kelime, emir kipi', max_length=60)),
                ('hook', models.CharField(help_text='Tek cümle — neden şimdi', max_length=160)),
                ('steps', models.JSONField(default=list, help_text='2-3 adım, her biri tek satır')),
                ('fallback', models.TextField(help_text='ZORUNLU: plan tutmazsa ne yapılır')),
                ('category', models.CharField(choices=[('ev_ici', 'Ev içi'), ('mutfak', 'Mutfak'), ('disari_yakin', 'Dışarı / yakın'), ('yeme_icme', 'Yeme-içme'), ('hareket', 'Hareket'), ('kultur', 'Kültür'), ('sosyal', 'Sosyal'), ('ogrenme', 'Öğrenme'), ('uretme', 'Üretme'), ('doga', 'Doğa'), ('kendine_bakim', 'Kendine bakım'), ('iyilik', 'İyilik'), ('oyun', 'Oyun'), ('ufak_isler', 'Ufak işler')], max_length=24)),
                ('cost_min', models.PositiveIntegerField(default=0, help_text='TL')),
                ('cost_max', models.PositiveIntegerField(default=0, help_text='TL')),
                ('cost_note', models.CharField(blank=True, max_length=80)),
                ('duration_min', models.PositiveSmallIntegerField(help_text='Dakika')),
                ('duration_max', models.PositiveSmallIntegerField(help_text='Dakika')),
                ('companions', models.JSONField(default=list, help_text='solo|couple|friends|family|kids')),
                ('energy', models.CharField(choices=[('low', 'Düşük'), ('medium', 'Orta'), ('high', 'Yüksek')], default='medium', max_length=8)),
                ('place', models.CharField(choices=[('ev', 'Evde'), ('yakin', 'Yürüme mesafesinde'), ('mekanli', 'Belirli tipte mekan gerekir')], max_length=8)),
                ('venue_type', models.CharField(blank=True, help_text="place=mekanli ise mekan TÜRÜ (ör: 'sinema'). İşletme ismi yazma.", max_length=40)),
                ('weather_need', models.CharField(choices=[('any', 'Fark etmez'), ('dry', 'Yağışsız olmalı'), ('warm', 'Ilık olmalı'), ('indoor', 'Kapalı alan')], default='any', max_length=8)),
                ('seasonality', models.JSONField(blank=True, default=list, help_text='Ay numaraları [1..12] veya boş = tüm yıl')),
                ('cultural_tags', models.JSONField(blank=True, default=list, help_text='ramazan, bayram, pazar_gunu, ay_sonu ...')),
                ('required_items', models.JSONField(blank=True, default=list, help_text='En fazla 3 madde')),
                ('theme_tags', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Kelime modu eşleşmesi')),
                ('night_unsafe_solo', models.BooleanField(default=False, help_text='Gece geç saatte tek başına önerilmesin')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Öneri',
                'verbose_name_plural': 'Öneriler',
                'ordering': ['slug'],
                'indexes': [models.Index(fields=['is_active', 'category'], name='core_sugges_is_acti_a9aa2f_idx'), models.Index(fields=['is_active', 'place'], name='core_sugges_is_acti_1b45f0_idx'), models.Index(fields=['is_active', 'cost_max'], name='core_sugges_is_acti_4f81ad_idx')],
            },
        ),
        migrations.CreateModel(
            name='SuggestionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('shown', 'Gösterildi'), ('saved', 'Kaydedildi'), ('dismissed', 'Geçildi'), ('done', 'Yapıldı')], default='shown', max_length=12)),
                ('dismissed_until', models.DateTimeField(blank=True, null=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('saved_at', models.DateTimeField(blank=True, null=True)),
                ('shown_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='core.anonprofile')),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='core.suggestion')),
            ],
            options={
                'verbose_name': 'Öneri durumu',
                'verbose_name_plural': 'Öneri durumları',
                'indexes': [models.Index(fields=['profile', 'status'], name='core_sugges_profile_303112_idx')],
                'constraints': [models.UniqueConstraint(fields=('profile', 'suggestion'), name='uniq_profile_suggestion')],
            },
        ),
    ]
