# Generated by Django 5.2.17 on 2026-09-12 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiRequestCache',
            fields=[
                ('signature', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.suggestion')),
            ],
            options={
                'verbose_name': 'AI önbelleği',
                'verbose_name_plural': 'AI önbellekleri',
            },
        ),
        migrations.CreateModel(
            name='AiUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anon_id', models.UUIDField()),
                ('day', models.DateField()),
                ('count', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'AI kullanımı',
                'verbose_name_plural': 'AI kullanımları',
                'constraints': [models.UniqueConstraint(fields=('anon_id', 'day'), name='uniq_ai_usage_day')],
            },
        ),
    ]
